### ISSUE TITLE
Convert to CSS hex "\e123"

### ISSUE THREAD

**Issue by gnowland** [ChazUK/vscode-unicode-converter#3]
Hello ChazUK, this is a handy little app but It would be great if there was an option to convert unicode to CSS hex (i.e. \e123)

Would you consider adding this functionality?

I suppose it would require bundling the [mathiasbynens/cssesc](https://github.com/mathiasbynens/cssesc) library as "he" of course wouldn't cover this use case 😊

**Comment by ChazUK** [comment]
Hi @gnowland Sorry this slipped my view.

I think that would be out of scope of this library as it would open it up to encoding/decoding more than just the standard. But feel free to fork it and adapt it.
